name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

/mnt/TsyrenD/Team5-spring-petclinic/.github/workflows    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run:  
        docker build  -t "tsyrend/petclinic:${{ github.sha }}" .
        docker images

    
