name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

<<<<<<< HEAD
    steps: 
  
=======
/mnt/TsyrenD/Team5-spring-petclinic/.github/workflows    steps:
>>>>>>> bd4326619d5da95405997285341aa23c7dbd5671
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run:  
        docker build  -t "tsyrend/petclinic:${{ github.sha }}" .
        docker images

    
